name: Run Tests
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run unit and integration tests (Jest)
        run: npm run test
      - name: Start the app (Vite) in background
        run: |
          npm run dev:ci &
          echo "Vite started in background"
        env:
          CI: true
      - name: Wait for Vite to start
        run: |
          echo "Waiting for Vite server..."
          npx wait-on http://localhost:5173 --timeout=120000 --interval=2000 --verbose
      - name: Run end-to-end tests (Cypress)
        run: npm run cypress:run
        env:
          DISPLAY: ':99'
