name: Run Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run unit and integration tests (Jest)
        run: npm run test
        
      - name: Install Cypress dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
        
      - name: Run end-to-end tests (Cypress)
        run: npm run test:e2e
        env:
          CYPRESS_RUN_BINARY: /home/runner/.cache/Cypress/14.4.0/Cypress/Cypress
